
INSERT INTO `fields` (`id`, `name`,`type`,`label`,`placeholder`,`component`) VALUES
(1, 'age', 'number', 'عمر بنا(سال)','نوساز = 0','input'),
(2, 'room', null,'تعداد اتاق',null,'select'),
(3, 'floor', 'number', ' طبقه','همکف = 0 و زیرزمین = 1-','input'),
(4, 'unit', 'number','تعداد کل واحد',null,'input'),
(5, 'has_loan', 'checkbox', 'وام دارد',null,'input'),
(6, 'loan_amount', 'number','مبلغ وام(تومان)',null,'input'),
(7, 'presell', 'checkbox', 'پیش فروش',null,'input'),
(8, 'delivery', null , 'زمان تحویل',null,'select'),
(9, 'tarakom','number','تراکم',null,'input'),
(10,'bahr','number','عرض زمین (متر)',null,'input'),
(11,'description',null,'توضیحات',null,'textarea'),
(12,'housting',null,'وضعیت سکونت',null,'select'),
(13,'doc',null,'نوع سند',null,'select'),
(14,'exchange','checkbox','معاوضه',null,'input'),
(15,'exchange_with','text','معاوضه با',null,'input'),
(16,'price','text','قیمت متر مربع (تومان)',null,'input'),
(17,'total_price','text','قیمت کل (تومان)',null,'input'),
(18,'facility','boolean','امکانات',null,'input')
;

INSERT INTO `options` (`id`,`field_id`,`value`,`label`) VALUES
(1, 8, null, 'انتخاب کنید'),
(2, 8, 1 , '1 ماه آینده'),
(3, 8, 2 , '2 ماه آینده'),
(4, 8, 3 ,'3 ماه آینده'),
(5, 8, 4 ,'4 ماه آینده'),
(6, 8, 5 ,'5 ماه آینده'),
(7, 8, 6 ,'6 ماه آینده'),
(8, 8, 7 ,'7 ماه آینده'),
(9, 8, 8 ,'8 ماه آینده'),
(10, 8, 9 ,'9 ماه آینده'),
(11, 8, 10 ,'10 ماه آینده'),
(12, 8, 11 ,'11 ماه آینده'),
(13, 8, 12 ,'12 ماه آینده'),
(14, 8, 13 ,'13 ماه آینده'),
(15, 8, 14 ,'14 ماه آینده'),
(16, 8, 15 ,'15 ماه آینده و بیشتر'),
(17, 2, 0 ,' بدون اتاق'),
(18, 2, 1 ,'1'),
(19, 2, 2 ,'2'),
(20, 2, 3 ,'3'),
(21, 2, 4 ,'4 و بیشتر'),
(22, 12, 'malek' ,'مالک سکونت دارد'),
(23, 12, 'mostajer' ,'مستاجر سکونت دارد'),
(24, 12, 'empty' ,'تخلیه'),
(25, 13, 'melki' ,'سند ملکی'),
(26, 13, 'oghafi' ,'اوقافی'),
(27, 13, 'gholnamei' ,'قلنامه ای'),
(28, 13, 'mosha' ,'مشاع'),
(29, 13, 'sarghofli' ,'سرقفلی')
;